<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A warm palette with serif headings, and a banner block. Copy it to start a theme of your own.' => 'Teplá paleta s pätkovými nadpismi a blok banner. Skopírujte ju a začnite vlastnú tému.',
    'Banner' => 'Banner',
    'Banner block' => 'Blok banner',
    'Link' => 'Odkaz',
    'Responsive' => 'Responzívny dizajn',
    'Serif headings' => 'Pätkové nadpisy',
    'Starter' => 'Štartovacia',
    'Text' => 'Text',
    'Warm colours' => 'Teplé farby',
];
